Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: usedid
          AttributeType: S
        - AttributeName: noteid
          AttributeType: S
      KeySchema:
        - AttributeName: usedid
          KeyType: HASH
        - AttributeName: noteid
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  StudentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNameStudent}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: studentId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: studentId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
